---
version: '3'
services:
  ftpd_server:
      image: stilliard/pure-ftpd
      container_name: pure-ftpd
      ports:
        - "21:21"
        - "30000-30009:30000-30009"
       
      environment:
        PUBLICHOST: "localhost"
        FTP_USER_NAME: bob
        FTP_USER_PASS: 12345
        FTP_USER_HOME: /home/bob

      restart: always

  web:
    image: machines/filestash
    container_name: filestash
    volumes:
      - ~/Course_project/config:/config
    ports:
      - 8334:8334
    restart: unless-stopped