---
apiVersion: v1
kind: Service
metadata:
  name: ftp-service
  namespace: default
spec:
  selector:
    app: ftp-server
  type: LoadBalancer
  ports:
  - name: ftp-service-port
    protocol: TCP
    port: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ftp-server
  namespace: default
  labels:
    app:  ftp-server
spec:
  selector:
    matchLabels:
      app: ftp-server
  replicas: 5
  template:
    metadata:
      labels:
        app:  ftp-server
    spec:
      containers:
      - name: my-ftp-container
        image: atmoz/sftp
        securityContext:
          privileged: true
        ports:
        - name: ftp-port
          containerPort: 22
        volumeMounts:
        - name: local
          mountPath: /shared
        - name: ssh-secret
          mountPath: /etc/ssh/ssh_host_rsa_key
          subPath: ssh_host_rsa_key
          readOnly: true
        - name: ssh-secret
          mountPath: /etc/ssh/ssh_host_ed25519_key
          subPath: ssh_host_ed25519_key
          readOnly: true
        - name: ftp-users
          mountPath: /etc/sftp/users.conf
          subPath: users.conf
          readOnly: true
        - name: link-pdir
          mountPath: /etc/sftp.d/link_pdir.sh
          subPath: link_pdir.sh
          readOnly: true     
      restartPolicy: Always
      
      volumes:
      - name: local
        persistentVolumeClaim:
          claimName: px-shared-pvc
      - name: ssh-secret
        secret: 
          secretName: ssh-privatekey
          defaultMode: 0400
      - name: ftp-users
        configMap:
          name: ftp-users
          defaultMode: 0400
      - name: link-pdir
        configMap:
          name: link-pdir
          defaultMode: 0500