---
apiVersion: v1
kind: Service
metadata:
  name: ftp-service
  namespace: default
spec:
  selector:
    app: ftp-server
  type: LoadBalancer
  ports:
  - name: ftp-service-port
    protocol: TCP
    port: 21
  - name: ftp-service-port--1
    protocol: TCP
    port: 30000
  - name: ftp-service-port-0
    protocol: TCP
    port: 30001
  - name: ftp-service-port-1
    protocol: TCP
    port: 30002
  - name: ftp-service-port-2
    protocol: TCP
    port: 30003
  - name: ftp-service-port-3
    protocol: TCP
    port: 30004
  - name: ftp-service-port-4
    protocol: TCP
    port: 30005
  - name: ftp-service-port-5
    protocol: TCP
    port: 30006
  - name: ftp-service-port-6
    protocol: TCP
    port: 30007
  - name: ftp-service-port-7
    protocol: TCP
    port: 30008
  - name: ftp-service-port-8
    protocol: TCP
    port: 30009
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ftp-server
  namespace: default
  labels:
    app:  ftp-server
spec:
  selector:
    matchLabels:
      app: ftp-server
  replicas: 1
  template:
    metadata:
      labels:
        app:  ftp-server
    spec:
      containers:
      - name:  ftp-server
        image:  stilliard/pure-ftpd
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PUBLICHOST
          value: "0.0.0.0"
        - name: FTP_USER_NAME
          value: "bob"
        - name: FTP_USER_PASS
          value: "12345"
        - name: FTP_USER_HOME
          value: "/home/bob"
        ports:
        - containerPort:  21
          protocol: TCP
          name:  ftp-server-port
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/bob
      restartPolicy: Always