---
apiVersion: v1
kind: Service
metadata:
  name: ftp-service
  namespace: default
spec:
  selector:
    app: ftp-service
  type: ClusterIP
  ports:
  - name: ftp-service
    protocol: TCP
    port: 21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ftp-server
  namespace: default
  labels:
    app:  ftp-server
spec:
  selector:
    matchLabels:
      app: ftp-server
  replicas: 2
  template:
    metadata:
      labels:
        app:  ftp-server
    spec:
      containers:
      - name:  ftp-server
        image:  stilliard/pure-ftpd
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PUBLICHOST
          value: "localhost"
        - name: FTP_USER_NAME
          value: "bob"
        - name: FTP_USER_PASS
          value: "12345"
        - name: FTP_USER_HOME
          value: "/home/bob"
        ports:
        - containerPort:  21
          protocol: TCP
          name:  ftp-server-port
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/bob
      restartPolicy: Always