---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ftp-ingress
spec:
  backend:
    serviceName: ftp-service
    servicePort: 21
---
apiVersion: v1
kind: Service
metadata:
  name: ftp-service
  namespace: default
spec:
  selector:
    app: ftp-server
  type: LoadBalancer
  ports:
  - name: ftp-service-port
    protocol: TCP
    port: 21
  - name: ftp-service-port--1
    protocol: TCP
    port: 30000
  - name: ftp-service-port-0
    protocol: TCP
    port: 30001
  - name: ftp-service-port-1
    protocol: TCP
    port: 30002
  - name: ftp-service-port-2
    protocol: TCP
    port: 30003
  - name: ftp-service-port-3
    protocol: TCP
    port: 30004
  - name: ftp-service-port-4
    protocol: TCP
    port: 30005
  - name: ftp-service-port-5
    protocol: TCP
    port: 30006
  - name: ftp-service-port-6
    protocol: TCP
    port: 30007
  - name: ftp-service-port-7
    protocol: TCP
    port: 30008
  - name: ftp-service-port-8
    protocol: TCP
    port: 30009
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: tp-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ftp
  hostPath:
    path: /home/ftp
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ftp-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ftp
  resources:
    requests:
      storage: 3Gi
---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: ftp-server
#   namespace: default
# spec:
#   selector:
#     matchLabels:
#       app: ftp-server # has to match .spec.template.metadata.labels
#   serviceName: "ftp-server"
#   replicas: 5 # by default is 1
#   template:
#     metadata:
#       labels:
#         app: ftp-server # has to match .spec.selector.matchLabels
#     spec:
#       terminationGracePeriodSeconds: 10
#       containers:
#       - name: ftp-server
#         image: stilliard/pure-ftpd
#         env:
#         - name: PUBLICHOST
#           value: "0.0.0.0"
#         - name: FTP_USER_NAME
#           value: "bob"
#         - name: FTP_USER_PASS
#           value: "12345"
#         - name: FTP_USER_HOME
#           value: "/home/bob"
#         ports:
#         - containerPort: 21
#           name: ftp-port
#         volumeMounts:
#         - name: www
#           mountPath: /usr/share/ftp_serv
#   volumeClaimTemplates:
#   - metadata:
#       name: www
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       storageClassName: "my-storage-class"
#       resources:
#         requests:
#           storage: 1Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ftp-server
  namespace: default
  labels:
    app:  ftp-server
spec:
  selector:
    matchLabels:
      app: ftp-server
  replicas: 5
  template:
    metadata:
      labels:
        app:  ftp-server
    spec:
      containers:
      - name:  ftp-server
        image:  stilliard/pure-ftpd
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PUBLICHOST
          value: "0.0.0.0"
        - name: FTP_USER_NAME
          value: "bob"
        - name: FTP_USER_PASS
          value: "12345"
        - name: FTP_USER_HOME
          value: "/home/bob"
        ports:
        - containerPort:  21
          protocol: TCP
          name:  ftp-server-port
      volumes:
        - name: local
          persistentVolumeClaim:
            claimName: ftp-claim
        # - name: localtime
        #   hostPath:
        #     path: /usr/share/bob
      restartPolicy: Always