---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
spec:
  selector:
    app: web-depl
  type: LoadBalancer
  ports:
  - name: web
    protocol: TCP
    port: 8334
    targetPort: 8334
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  web-depl
  namespace: default
  labels:
    app:  web-depl
spec:
  selector:
    matchLabels:
      app: web-depl
  replicas: 5
  template:
    metadata:
      labels:
        app:  web-depl
    spec:
      containers:
      - name:  web-depl
        image:  machines/filestash
        ports:
        - containerPort:  8334
          name:  web
      volumes:
        - name: localtime
          hostPath:
            path: ~/Course_project/config:/config
      restartPolicy: Always

